AWSTemplateFormatVersion: 2010-09-09
Description: >
  cover validator

Globals:
  Api:
    OpenApiVersion: 3.0.1

  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100
    Layers:
      - Ref: RuntimeDependenciesLayer

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Type: String

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: Cover Validator ${ENV}
      StageName: !Ref ENV

  AddBuildConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/addBuildConfig.handler
      Description: add build config
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /add-build-config
            Method: POST

  UpdateBuildConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/updateBuildConfig.handler
      Description: update build config
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /update-build-config
            Method: PUT

  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
