AWSTemplateFormatVersion: 2010-09-09
Description: Cover Validator

Globals:
  Api:
    OpenApiVersion: 3.0.1
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        NODE_ENV: !Ref Env
        COVER_CANISTER_ID: !Ref CoverCanisterId

Transform:
  - AWS::Serverless-2016-10-31

# Default as local environment
Parameters:
  Env:
    Type: String
    Description: Environment
    Default: local
  CoverCanisterId:
    Type: String
    Description: Cover canister id
    Default: rrkah-fqaaa-aaaaa-aaaaq-cai
  SecretArn:
    Type: String
    Description: Secret Manager

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: Cover Validator ${Env}
      StageName: !Ref Env

  SaveBuildConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/saveBuildConfig.handler
      Description: save build config
      Events:
        SaveBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /save-build-config
            Method: POST
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretArn}

  BuildWithConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/buildWithConfig.handler
      Description: build with config
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /build-with-config
            Method: POST
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretArn}

  BuildFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/build.handler
      Description: build wasm
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /build
            Method: POST
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretArn}
