AWSTemplateFormatVersion: 2010-09-09
Description: >
  cover validator

Globals:
  Api:
    OpenApiVersion: 3.0.1

  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        NODE_ENV: !Ref Env
        COVER_CANISTER_ID: !Ref CoverCanisterId
        SECRET_KEY: !Ref SecretKey

Transform:
  - AWS::Serverless-2016-10-31

# Default as local environment
Parameters:
  Env:
    Type: String
    Description: Environment
    Default: local
  CoverCanisterId:
    Type: String
    Description: Cover canister id
    Default: rrkah-fqaaa-aaaaa-aaaaq-cai
  SecretKey:
    Type: String
    Description: SecretKey to get secret data from AWS KMS

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: Cover Validator ${Env}
      StageName: !Ref Env

  AddBuildConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/addBuildConfig.handler
      Description: add build config
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /add-build-config
            Method: POST

  UpdateBuildConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/updateBuildConfig.handler
      Description: update build config
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /update-build-config
            Method: PUT

  BuildWasmFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/buildWasm.handler
      Description: build wasm
      Events:
        AddBuildConfigApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /build-wasm
            Method: POST
